In [1]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
tf.set_random_seed(777)  # for reproducibility

In [3]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [4]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [5]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [6]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [7]:
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [8]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  77437.836 
Prediction:
 [ -99.19784 -109.40472 -112.99919 -123.97137  -79.7757 ]
10 Cost:  10.199709 
Prediction:
 [146.9667  186.44461 178.51767 193.4821  145.8782 ]
20 Cost:  9.441354 
Prediction:
 [147.72311 187.33174 179.40321 194.44539 146.55028]
30 Cost:  9.392067 
Prediction:
 [147.737   187.32648 179.40942 194.4511  146.54167]
40 Cost:  9.343039 
Prediction:
 [147.74861 187.31851 179.41298 194.45387 146.53104]
50 Cost:  9.294299 
Prediction:
 [147.76016 187.31058 179.41647 194.45663 146.5204 ]
60 Cost:  9.245787 
Prediction:
 [147.7717  187.30264 179.41998 194.45941 146.50981]
70 Cost:  9.197588 
Prediction:
 [147.78319 187.29474 179.42348 194.46216 146.49925]
80 Cost:  9.149615 
Prediction:
 [147.79465 187.28685 179.42696 194.4649  146.48871]
90 Cost:  9.1018915 
Prediction:
 [147.8061  187.27899 179.43044 194.46764 146.47821]
100 Cost:  9.054449 
Prediction:
 [147.81749 187.27113 179.43388 194.47038 146.46773]
110 Cost:  9.007288 
Prediction:
 [147.82886 187.26335 17

1300 Cost:  4.8766813 
Prediction:
 [148.98235 186.46986 179.78732 194.75291 145.39355]
1310 Cost:  4.852012 
Prediction:
 [148.99051 186.46422 179.78978 194.75493 145.38596]
1320 Cost:  4.8274727 
Prediction:
 [148.99872 186.45863 179.79231 194.75697 145.37843]
1330 Cost:  4.8030415 
Prediction:
 [149.00685 186.45302 179.79475 194.75897 145.37086]
1340 Cost:  4.778758 
Prediction:
 [149.01498 186.44742 179.79721 194.76099 145.36336]
1350 Cost:  4.754628 
Prediction:
 [149.02307 186.44185 179.79967 194.76297 145.35585]
1360 Cost:  4.730642 
Prediction:
 [149.03116 186.43631 179.80212 194.76495 145.34839]
1370 Cost:  4.706728 
Prediction:
 [149.03922 186.43076 179.80457 194.76694 145.34091]
1380 Cost:  4.6829753 
Prediction:
 [149.04724 186.42523 179.80698 194.76892 145.33347]
1390 Cost:  4.65935 
Prediction:
 [149.05525 186.41971 179.80943 194.77089 145.32605]
1400 Cost:  4.635835 
Prediction:
 [149.06323 186.4142  179.81184 194.77286 145.31863]
1410 Cost:  4.6124625 
Prediction:
 [149

위 방법은 복잡해서 사용하지 않음.
## MATRIX
로 표현하기!

In [9]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [10]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [11]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [12]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [13]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [14]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  105818.3 
Prediction:
 [[-133.5243 ]
 [-164.79396]
 [-160.21033]
 [-174.73906]
 [-126.36729]]
10 Cost:  8.3119755 
Prediction:
 [[154.21864]
 [181.07106]
 [180.56627]
 [196.35913]
 [137.44464]]
20 Cost:  7.3049765 
Prediction:
 [[155.07903]
 [182.12459]
 [181.59424]
 [197.47952]
 [138.25221]]
30 Cost:  7.266832 
Prediction:
 [[155.07141]
 [182.13478]
 [181.59424]
 [197.4805 ]
 [138.264  ]]
40 Cost:  7.228904 
Prediction:
 [[155.0612 ]
 [182.14182]
 [181.59116]
 [197.47812]
 [138.27338]]
50 Cost:  7.1911354 
Prediction:
 [[155.05101]
 [182.14882]
 [181.58803]
 [197.47568]
 [138.2827 ]]
60 Cost:  7.1536226 
Prediction:
 [[155.04083]
 [182.15579]
 [181.58493]
 [197.4733 ]
 [138.29199]]
70 Cost:  7.116286 
Prediction:
 [[155.03072]
 [182.16277]
 [181.58186]
 [197.47089]
 [138.30128]]
80 Cost:  7.079152 
Prediction:
 [[155.0206 ]
 [182.16971]
 [181.57877]
 [197.4685 ]
 [138.31053]]
90 Cost:  7.0422335 
Prediction:
 [[155.01053]
 [182.17665]
 [181.57571]
 [197.46614]
 [138.31976]]
1

1030 Cost:  4.3289337 
Prediction:
 [[154.17587]
 [182.75034]
 [181.32188]
 [197.2675 ]
 [139.08533]]
1040 Cost:  4.306825 
Prediction:
 [[154.16809]
 [182.75569]
 [181.3195 ]
 [197.26564]
 [139.09248]]
1050 Cost:  4.284869 
Prediction:
 [[154.16032]
 [182.76102]
 [181.31717]
 [197.26376]
 [139.09961]]
1060 Cost:  4.2630363 
Prediction:
 [[154.1526 ]
 [182.76634]
 [181.31482]
 [197.26192]
 [139.10672]]
1070 Cost:  4.2413077 
Prediction:
 [[154.14488]
 [182.77164]
 [181.31247]
 [197.26007]
 [139.11382]]
1080 Cost:  4.2197065 
Prediction:
 [[154.13719]
 [182.77693]
 [181.31013]
 [197.25822]
 [139.12088]]
1090 Cost:  4.1981974 
Prediction:
 [[154.12952]
 [182.7822 ]
 [181.3078 ]
 [197.25636]
 [139.12794]]
1100 Cost:  4.1768045 
Prediction:
 [[154.12187]
 [182.78746]
 [181.30547]
 [197.25453]
 [139.135  ]]
1110 Cost:  4.1555634 
Prediction:
 [[154.11424]
 [182.79271]
 [181.30316]
 [197.2527 ]
 [139.142  ]]
1120 Cost:  4.1344047 
Prediction:
 [[154.10663]
 [182.79794]
 [181.30087]
 [197.250