In [1]:
import numpy as np
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
tf.set_random_seed(777)  # for reproducibility

In [3]:
# nan-normalized inputs
# 아래와 같이 데이터에 지나치게 큰 숫자가 섞여있는 경우
# 비용함수가 한쪽으로 치우쳐지개 된다.
# 그래프 바깥으로 튕겨 나감

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

### 아래와 같이 정규화 과정을 거치면 정상적인 값을 얻을 수 있다
    def min_max_scaler(data):
        numerator = data - np.min(data, 0)
        denominator = np.max(data, 0) - np.min(data, 0)
        # noise term prevents the zero division
        return numerator / (denominator + 1e-7)

    # very important. It does not work without it.
    xy = min_max_scaler(xy)

In [4]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [5]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [6]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [7]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  111031470000.0 
Prediction:
 [[235671.06]
 [474241.3 ]
 [373106.84]
 [261600.1 ]
 [308277.25]
 [310872.47]
 [284938.03]
 [362737.06]]
1 Cost:  1.2198808e+26 
Prediction:
 [[-7.7909427e+12]
 [-1.5683966e+13]
 [-1.2338011e+13]
 [-8.6488803e+12]
 [-1.0193166e+13]
 [-1.0278961e+13]
 [-9.4210233e+12]
 [-1.1994835e+13]]
2 Cost:  inf 
Prediction:
 [[2.5824131e+20]
 [5.1986620e+20]
 [4.0895999e+20]
 [2.8667878e+20]
 [3.3786627e+20]
 [3.4071001e+20]
 [3.1227253e+20]
 [3.9758499e+20]]
3 Cost:  inf 
Prediction:
 [[-8.5597556e+27]
 [-1.7231666e+28]
 [-1.3555529e+28]
 [-9.5023541e+27]
 [-1.1199032e+28]
 [-1.1293293e+28]
 [-1.0350693e+28]
 [-1.3178490e+28]]
4 Cost:  inf 
Prediction:
 [[2.8372465e+35]
 [5.7116684e+35]
 [4.4931634e+35]
 [3.1496837e+35]
 [3.7120704e+35]
 [3.7433144e+35]
 [3.4308769e+35]
 [4.3681885e+35]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]